export { default as WishlistPage } from "./wishlist-page/WishlistPage";
export { default as Homepage } from "./homepage/Homepage";
export { default as CartPage } from "./cartpage/CartPage";
export { default as ProductsPage } from "./products-page/ProductsPage";
export { default as SearchPage } from "./search-page/SearchPage";
export { default as SignInPage } from "./signin-page/SignInPage";
export { default as SignUpPage } from "./signup-page/SignUpPage";
export { default as ProfilePage } from "./profile-page/ProfilePage";
export { default as ProductPage } from "./product-page/ProductPage";
